version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 8
    labels:
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'deps'
    groups:
      frameworks:
        patterns:
          - 'next'
          - '@next/*'
          - 'nuxt'
          - '@nuxt/*'
          - 'react'
          - 'react-*'
          - '@react-*/*'
          - 'vue'
          - '@vue/*'
          - 'payload'
          - '@payloadcms/*'
          - '@adonisjs/*'
      typescript-eslint:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'eslint'
          - 'eslint-*'
          - '@eslint/*'
          - '@typescript-eslint/*'
      testing:
        patterns:
          - 'vitest'
          - '@vitest/*'
          - 'playwright'
          - '@playwright/*'
          - '@testing-library/*'
          - '@japa/*'
      build-tooling:
        patterns:
          - 'turbo'
          - 'tsx'
          - 'prettier'
          - '@swc/*'
          - 'vite'
          - 'vue-tsc'
      ui-and-icons:
        patterns:
          - '@iconify/*'
          - 'lucide*'
          - '@unovis/*'
          - 'vee-validate'
      misc-patch:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'deps'

  - package-ecosystem: 'docker'
    directory: '/apps/backend'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'deps'

  - package-ecosystem: 'docker'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'deps'

  - package-ecosystem: 'docker'
    directory: '/apps/studio'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'dependabot'
    commit-message:
      prefix: 'deps'
