/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    spaces: Space;
    posts: Post;
    pages: Page;
    categories: Category;
    tags: Tag;
    redirects: Redirect;
    forms: Form;
    'form-fields': FormField;
    'form-submissions': FormSubmission;
    'form-submission-values': FormSubmissionValue;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-fields': FormFieldsSelect<false> | FormFieldsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'form-submission-values': FormSubmissionValuesSelect<false> | FormSubmissionValuesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Display name for the tenant/site
   */
  name: string;
  /**
   * URL-friendly identifier for the tenant
   */
  slug: string;
  /**
   * Custom domain for this tenant
   */
  domain: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'content_admin' | 'editor' | 'publisher' | 'user';
  firstName?: string | null;
  lastName?: string | null;
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * URL-friendly identifier (unique per owner)
   */
  slug: string;
  /**
   * Display name for the space
   */
  name: string;
  /**
   * Optional description of the space
   */
  description?: string | null;
  /**
   * User who owns this space (synced with tenant from multi-tenant plugin)
   */
  owner: number | User;
  /**
   * If true, this is the default space for articles
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Title of the blog post
   */
  title: string;
  /**
   * Unique URL for this post (e.g., yoursite.com/posts/{{slug}})
   */
  slug: string;
  /**
   * Short summary of the blog post
   */
  description?: string | null;
  /**
   * Rich text content of your blog post
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Featured image for this post
   */
  image?: (number | null) | Media;
  /**
   * Select the team member who wrote this post
   */
  author: number | User;
  /**
   * The space this post belongs to (if empty, defaults to author's default space)
   */
  space?: (number | null) | Space;
  /**
   * Is this post published?
   */
  status: 'draft' | 'in_review' | 'published';
  /**
   * Publish now or schedule for later
   */
  publishedAt?: string | null;
  type: 'article' | 'audio' | 'video';
  /**
   * Categories for this post
   */
  categories?: (number | Category)[] | null;
  /**
   * Tags for this post
   */
  tags?: (number | Tag)[] | null;
  seo?: {
    /**
     * SEO title (overrides post title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
    /**
     * Open Graph image
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Category title
   */
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional description
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Tag name
   */
  name: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Optional color (e.g., #AABBCC)
   */
  color?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * The title of this page
   */
  title: string;
  /**
   * Unique URL for this page (start with /, can have multiple segments /about/me)
   */
  permalink: string;
  /**
   * Is this page published?
   */
  status: 'draft' | 'in_review' | 'published';
  /**
   * Publish now or schedule for later
   */
  publishedAt?: string | null;
  /**
   * Create and arrange different content blocks to build your page
   */
  blocks?:
    | (
        | {
            tagline?: string | null;
            headline?: string | null;
            description?: string | null;
            image?: (number | null) | Media;
            layout?: ('image_left' | 'image_center' | 'image_right') | null;
            buttons?:
              | {
                  label: string;
                  type: 'page' | 'post' | 'url';
                  page?: (number | null) | Page;
                  post?: (number | null) | Post;
                  url?: string | null;
                  variant?: ('default' | 'outline' | 'soft' | 'ghost' | 'link') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richtext';
          }
        | {
            tagline?: string | null;
            headline?: string | null;
            items?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            tagline?: string | null;
            headline?: string | null;
            collection: 'posts';
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'posts';
          }
        | {
            tagline?: string | null;
            headline?: string | null;
            pricingCards?:
              | {
                  title: string;
                  description?: string | null;
                  price?: string | null;
                  badge?: string | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  button: {
                    label: string;
                    type: 'page' | 'post' | 'url';
                    page?: (number | null) | Page;
                    post?: (number | null) | Post;
                    url?: string | null;
                  };
                  isHighlighted?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            tagline?: string | null;
            headline?: string | null;
            form?: (number | null) | Form;
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
      )[]
    | null;
  seo?: {
    /**
     * SEO title (overrides page title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
    /**
     * Open Graph image
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Form name (for internal reference).
   */
  title: string;
  /**
   * Show or hide this form from the site.
   */
  isActive?: boolean | null;
  fields?: (number | FormField)[] | null;
  /**
   * Text shown on submit button.
   */
  submitLabel?: string | null;
  /**
   * Action after successful submission.
   */
  onSuccess?: ('redirect' | 'message') | null;
  /**
   * Message shown after successful submission.
   */
  successMessage?: string | null;
  /**
   * Destination URL after successful submission.
   */
  successRedirectUrl?: string | null;
  /**
   * Setup email notifications when forms are submitted.
   */
  emails?:
    | {
        to?:
          | {
              email?: string | null;
              id?: string | null;
            }[]
          | null;
        subject?: string | null;
        message?: string | null;
        id?: string | null;
      }[]
    | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-fields".
 */
export interface FormField {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Unique field identifier, not shown to users (lowercase, hyphenated)
   */
  name: string;
  /**
   * Text label shown to form users.
   */
  label: string;
  /**
   * Input type for the field
   */
  type: 'text' | 'textarea' | 'checkbox' | 'checkbox_group' | 'radio' | 'file' | 'select' | 'hidden';
  /**
   * Default text shown in empty input.
   */
  placeholder?: string | null;
  /**
   * Additional instructions shown below the input
   */
  help?: string | null;
  /**
   * Available rules: `email`, `url`, `min:5`, `max:20`, `length:10`. Combine with pipes example: `email|max:255`
   */
  validation?: string | null;
  /**
   * Make this field mandatory to complete.
   */
  required?: boolean | null;
  /**
   * Field width on the form
   */
  width?: ('100' | '67' | '50' | '33') | null;
  /**
   * Options for radio or select inputs
   */
  choices?:
    | {
        text: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Parent form this field belongs to.
   */
  form?: (number | null) | Form;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old URL (relative to site, e.g., /blog or /news)
   */
  urlFrom: string;
  /**
   * The URL you're redirecting to (can be relative or full URL)
   */
  urlTo: string;
  /**
   * HTTP response code for the redirect
   */
  responseCode: '301' | '302';
  /**
   * Short explanation of why the redirect was created
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  tenant?: (number | null) | Tenant;
  form: number | Form;
  values?: (number | FormSubmissionValue)[] | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-values".
 */
export interface FormSubmissionValue {
  id: number;
  tenant?: (number | null) | Tenant;
  submission: number | FormSubmission;
  field: number | FormField;
  value: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'spaces';
        value: number | Space;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-fields';
        value: number | FormField;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'form-submission-values';
        value: number | FormSubmissionValue;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  tenant?: T;
  slug?: T;
  name?: T;
  description?: T;
  owner?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  content?: T;
  image?: T;
  author?: T;
  space?: T;
  status?: T;
  publishedAt?: T;
  type?: T;
  categories?: T;
  tags?: T;
  seo?:
    | T
    | {
        title?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  permalink?: T;
  status?: T;
  publishedAt?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              tagline?: T;
              headline?: T;
              description?: T;
              image?: T;
              layout?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    post?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richtext?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              tagline?: T;
              headline?: T;
              items?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        posts?:
          | T
          | {
              tagline?: T;
              headline?: T;
              collection?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              tagline?: T;
              headline?: T;
              pricingCards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    price?: T;
                    badge?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    button?:
                      | T
                      | {
                          label?: T;
                          type?: T;
                          page?: T;
                          post?: T;
                          url?: T;
                        };
                    isHighlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              tagline?: T;
              headline?: T;
              form?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  slug?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  urlFrom?: T;
  urlTo?: T;
  responseCode?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  isActive?: T;
  fields?: T;
  submitLabel?: T;
  onSuccess?: T;
  successMessage?: T;
  successRedirectUrl?: T;
  emails?:
    | T
    | {
        to?:
          | T
          | {
              email?: T;
              id?: T;
            };
        subject?: T;
        message?: T;
        id?: T;
      };
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-fields_select".
 */
export interface FormFieldsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  label?: T;
  type?: T;
  placeholder?: T;
  help?: T;
  validation?: T;
  required?: T;
  width?: T;
  choices?:
    | T
    | {
        text?: T;
        value?: T;
        id?: T;
      };
  form?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  tenant?: T;
  form?: T;
  values?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submission-values_select".
 */
export interface FormSubmissionValuesSelect<T extends boolean = true> {
  tenant?: T;
  submission?: T;
  field?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Site name
   */
  siteName: string;
  /**
   * Site description
   */
  siteDescription?: string | null;
  /**
   * Site logo
   */
  logo?: (number | null) | Media;
  /**
   * Site favicon
   */
  favicon?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Navigation menu items
   */
  items?:
    | {
        label: string;
        type: 'page' | 'post' | 'url';
        page?: (number | null) | Page;
        post?: (number | null) | Post;
        /**
         * The URL to link to. Could be relative (ie /my-page) or a full external URL
         */
        url?: string | null;
        /**
         * Nested navigation items
         */
        children?:
          | {
              label: string;
              type: 'page' | 'post' | 'url';
              page?: (number | null) | Page;
              post?: (number | null) | Post;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  logo?: T;
  favicon?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        post?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              type?: T;
              page?: T;
              post?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}