import type { SeedMediaRef, SeedPost } from './types'

const day = 24 * 60 * 60 * 1000
const now = Date.now()
const isoDaysAgo = (daysAgo: number) => new Date(now - daysAgo * day).toISOString()

export const seedMediaLibrary: SeedMediaRef[] = [
  { key: 'war-room', url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1400&h=900&fit=crop', alt: 'Team working in a project war room' },
  { key: 'keyboard', url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1400&h=900&fit=crop', alt: 'Close-up of keyboard and workstation' },
  { key: 'whiteboard', url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1400&h=900&fit=crop', alt: 'Planning notes on a whiteboard' },
  { key: 'dashboard', url: 'https://images.unsplash.com/photo-1551281044-8b5bd3f4f5d2?w=1400&h=900&fit=crop', alt: 'Analytics dashboard on a monitor' },
  { key: 'meeting', url: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=1400&h=900&fit=crop', alt: 'Cross-functional team meeting' },
  { key: 'ops', url: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=1400&h=900&fit=crop', alt: 'Operations command center' },
  { key: 'cost', url: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1400&h=900&fit=crop', alt: 'Finance report on laptop screen' },
  { key: 'pipeline', url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1400&h=900&fit=crop', alt: 'Code on screen during development' },
  { key: 'remote-team', url: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1400&h=900&fit=crop', alt: 'Remote team collaboration call' },
  { key: 'strategy', url: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=1400&h=900&fit=crop', alt: 'Product strategy workshop' },
  { key: 'docs', url: 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=1400&h=900&fit=crop', alt: 'Notebook and documentation desk' },
  { key: 'deploy', url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1400&h=900&fit=crop', alt: 'Code deployment workflow screen' },
]

type Blueprint = {
  title: string
  slug: string
  description: string
  topic: string
  listType: 'bullet' | 'number'
  listItems: string[]
  quote: string
  quoteBy: string
  status: 'draft' | 'in_review' | 'published'
  type: 'article' | 'audio' | 'video'
  featuredImageKey: string
  inlineImageKey?: string
  daysAgo: number
}

const blueprints: Blueprint[] = [
  { title: 'Incident Postmortems That Actually Change Team Behavior', slug: 'incident-postmortems-that-change-team-behavior', description: 'A practical framework for turning incidents into measurable reliability gains.', topic: 'postmortem follow-through', listType: 'number', listItems: ['Record the triggering condition in system terms.', 'Assign one owner per corrective action with a due date.', 'Review remediation progress in weekly engineering ops.'], quote: 'The quality of the follow-up is the quality of the postmortem.', quoteBy: 'Reliability Lead', status: 'published', type: 'article', featuredImageKey: 'war-room', inlineImageKey: 'whiteboard', daysAgo: 3 },
  { title: 'Feature Flags in Multi-Tenant SaaS Without Configuration Debt', slug: 'feature-flags-in-multi-tenant-saas-without-configuration-debt', description: 'How to structure flags by audience and lifecycle so stale toggles do not accumulate.', topic: 'flag lifecycle policy', listType: 'bullet', listItems: ['Declare owner and expected removal date at creation time.', 'Separate rollout flags from permanent entitlement rules.', 'Archive retired flags monthly with usage evidence.'], quote: 'A flag without an expiry date is future architecture debt.', quoteBy: 'Platform Architect', status: 'published', type: 'article', featuredImageKey: 'deploy', inlineImageKey: 'meeting', daysAgo: 6 },
  { title: 'Designing API Error Contracts for Faster Frontend Debugging', slug: 'designing-api-error-contracts-for-faster-frontend-debugging', description: 'Error responses that improve operator visibility and reduce support round-trips.', topic: 'api error contracts', listType: 'bullet', listItems: ['Return stable machine error codes for every known class.', 'Attach remediation hints that point to the next user action.', 'Keep dependency failures separate from validation failures.'], quote: 'Predictable errors reduce support latency more than perfect docs.', quoteBy: 'API Maintainer', status: 'published', type: 'article', featuredImageKey: 'keyboard', inlineImageKey: 'dashboard', daysAgo: 9 },
  { title: 'Production Readiness Checklist for New Background Workers', slug: 'production-readiness-checklist-for-new-background-workers', description: 'Queue visibility, retries, and idempotency checks before your first high-volume run.', topic: 'worker readiness', listType: 'number', listItems: ['Define idempotency key and replay safety boundaries.', 'Set retry budget with dead-letter escape hatch.', 'Expose lag, throughput, and failure metrics before launch.'], quote: 'Workers are production code, not hidden automation.', quoteBy: 'Staff Engineer', status: 'published', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'pipeline', daysAgo: 12 },
  { title: 'Schema Evolution in Event-Driven Systems', slug: 'schema-evolution-in-event-driven-systems', description: 'Versioning approaches that preserve compatibility across independent consumers.', topic: 'event schema compatibility', listType: 'bullet', listItems: ['Prefer additive changes over field replacement.', 'Replay production samples in compatibility tests.', 'Document deprecation windows in the schema repo.'], quote: 'Independent deployability depends on contract discipline.', quoteBy: 'Data Platform Team', status: 'published', type: 'article', featuredImageKey: 'pipeline', inlineImageKey: 'dashboard', daysAgo: 16 },
  { title: 'An Opinionated CI Pipeline for TypeScript Monorepos', slug: 'opinionated-ci-pipeline-for-typescript-monorepos', description: 'A staged pipeline that balances speed, determinism, and actionable feedback.', topic: 'ci pipeline design', listType: 'number', listItems: ['Run lint and typecheck as fast pre-merge gates.', 'Parallelize test shards by package ownership.', 'Publish flaky-test report with weekly cleanup target.'], quote: 'Fast feedback wins only when it stays trustworthy.', quoteBy: 'Developer Experience Team', status: 'published', type: 'article', featuredImageKey: 'deploy', inlineImageKey: 'keyboard', daysAgo: 20 },
  { title: 'Writing Better Internal Docs for High-Change Systems', slug: 'writing-better-internal-docs-for-high-change-systems', description: 'Documentation patterns that stay relevant after rapid iteration cycles.', topic: 'internal docs strategy', listType: 'bullet', listItems: ['Lead with decision context before implementation detail.', 'Add owner and review cadence on every document.', 'Track stale pages with quarterly doc health reports.'], quote: 'Documentation is operational tooling for future teammates.', quoteBy: 'Engineering Manager', status: 'draft', type: 'article', featuredImageKey: 'docs', inlineImageKey: 'docs', daysAgo: 25 },
  { title: 'Pragmatic Database Indexing for Product Teams', slug: 'pragmatic-database-indexing-for-product-teams', description: 'When to add indexes, when to remove them, and how to verify impact safely.', topic: 'database indexing tradeoffs', listType: 'number', listItems: ['Start from slow query logs, not assumptions.', 'Measure write amplification before adding new indexes.', 'Cull unused indexes using monthly access snapshots.'], quote: 'Every index is a speedup for one path and drag for another.', quoteBy: 'Database Engineer', status: 'published', type: 'article', featuredImageKey: 'dashboard', inlineImageKey: 'strategy', daysAgo: 28 },
  { title: 'Observability Baseline for Teams Shipping Weekly', slug: 'observability-baseline-for-teams-shipping-weekly', description: 'A minimum viable telemetry model for confident and frequent releases.', topic: 'observability baseline', listType: 'bullet', listItems: ['Track user journey symptoms before internal counters.', 'Map alerts to runbooks with clear first actions.', 'Review alert noise ratio in each sprint retro.'], quote: 'If you cannot explain an alert, you cannot trust it.', quoteBy: 'SRE Team', status: 'draft', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'dashboard', daysAgo: 33 },
  { title: 'Reliable Bulk Imports with Idempotent Keys', slug: 'reliable-bulk-imports-with-idempotent-keys', description: 'Prevent duplicate records and partial corruption during large ingest jobs.', topic: 'bulk import idempotency', listType: 'number', listItems: ['Use deterministic natural keys for dedupe.', 'Persist row-level outcomes for replay safety.', 'Emit reconciliation reports for business owners.'], quote: 'Bulk jobs fail safely only when retries are deterministic.', quoteBy: 'Data Integrations Team', status: 'published', type: 'article', featuredImageKey: 'whiteboard', inlineImageKey: 'pipeline', daysAgo: 40 },
  { title: 'Running Cost Reviews Without Slowing Delivery Teams', slug: 'running-cost-reviews-without-slowing-delivery-teams', description: 'A lightweight operating cadence for cloud cost accountability and faster tradeoff decisions.', topic: 'cloud cost operations', listType: 'number', listItems: ['Review top spend deltas since last release window.', 'Select one savings action per squad per month.', 'Reinvest measured savings into reliability initiatives.'], quote: 'Cost ownership works when it is routine, not punitive.', quoteBy: 'Finance Partner', status: 'published', type: 'article', featuredImageKey: 'cost', inlineImageKey: 'cost', daysAgo: 45 },
  { title: 'Release Trains vs Continuous Delivery in B2B Platforms', slug: 'release-trains-vs-continuous-delivery-in-b2b-platforms', description: 'How to choose a release model based on customer coordination and platform coupling.', topic: 'release model selection', listType: 'bullet', listItems: ['Use trains when coordinated customer communication is mandatory.', 'Use continuous delivery for independently deployable surfaces.', 'Mix models by domain to reduce coupling risk.'], quote: 'Release strategy should reflect customer dependency shape.', quoteBy: 'Product Operations', status: 'published', type: 'article', featuredImageKey: 'meeting', inlineImageKey: 'strategy', daysAgo: 49 },
  { title: 'Turning Support Tickets Into Product Discovery Inputs', slug: 'turning-support-tickets-into-product-discovery-inputs', description: 'A repeatable method for converting recurring support pain into roadmap direction.', topic: 'support-driven discovery', listType: 'number', listItems: ['Tag tickets by friction type and account tier.', 'Estimate lost time and churn risk per pattern.', 'Turn top patterns into measurable discovery bets.'], quote: 'Support is your fastest path to user truth.', quoteBy: 'Customer Success Lead', status: 'in_review', type: 'article', featuredImageKey: 'war-room', inlineImageKey: 'meeting', daysAgo: 52 },
  { title: 'Designing Better On-Call Rotations for Small Teams', slug: 'designing-better-oncall-rotations-for-small-teams', description: 'Reduce burnout with practical constraints, escalation policy, and incident follow-through.', topic: 'on-call health', listType: 'bullet', listItems: ['Guarantee protected recovery blocks after major incidents.', 'Calibrate schedule by incident volume, not team size.', 'Review escalation path clarity every quarter.'], quote: 'A humane rota is a reliability feature.', quoteBy: 'Engineering Director', status: 'published', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'remote-team', daysAgo: 58 },
  { title: 'Service Ownership Templates That Scale Across Squads', slug: 'service-ownership-templates-that-scale-across-squads', description: 'Define ownership expectations once and keep runtime operations consistent.', topic: 'service ownership templates', listType: 'number', listItems: ['Define escalation contacts and response windows.', 'Document dependencies with blast radius notes.', 'Track reliability debt as visible backlog work.'], quote: 'Ownership clarity shortens every incident timeline.', quoteBy: 'Platform Program Manager', status: 'published', type: 'article', featuredImageKey: 'whiteboard', inlineImageKey: 'whiteboard', daysAgo: 63 },
  { title: 'API Versioning Policy for Fast-Moving Product Teams', slug: 'api-versioning-policy-for-fast-moving-product-teams', description: 'Balance backward compatibility with product velocity using explicit change classes.', topic: 'api lifecycle governance', listType: 'bullet', listItems: ['Classify changes as additive, behavioral, or breaking.', 'Automate compatibility checks against key clients.', 'Publish deprecation timelines in release notes.'], quote: 'Versioning is less about numbers and more about promises.', quoteBy: 'API Council', status: 'draft', type: 'article', featuredImageKey: 'deploy', inlineImageKey: 'keyboard', daysAgo: 68 },
  { title: 'Data Retention Rules Developers Can Actually Apply', slug: 'data-retention-rules-developers-can-actually-apply', description: 'Translate policy language into implementation-ready retention and deletion patterns.', topic: 'data retention implementation', listType: 'number', listItems: ['Map each data type to legal basis and retention term.', 'Build deletion jobs with audit evidence output.', 'Define legal hold exceptions in one shared workflow.'], quote: 'Policy is useful only when it ships as automation.', quoteBy: 'Compliance Engineer', status: 'published', type: 'article', featuredImageKey: 'dashboard', inlineImageKey: 'docs', daysAgo: 73 },
  { title: 'Queue Backpressure Strategies for Event Pipelines', slug: 'queue-backpressure-strategies-for-event-pipelines', description: 'Operational patterns to protect downstream dependencies under burst traffic.', topic: 'queue backpressure', listType: 'bullet', listItems: ['Throttle producers when lag exceeds policy window.', 'Prioritize critical traffic lanes during spikes.', 'Rehearse replay paths for dead-letter recovery.'], quote: 'Backpressure protects users from invisible overload.', quoteBy: 'Runtime Team', status: 'published', type: 'article', featuredImageKey: 'pipeline', inlineImageKey: 'ops', daysAgo: 79 },
  { title: 'Migration Playbook for Splitting Monolithic Services', slug: 'migration-playbook-for-splitting-monolithic-services', description: 'A phased migration model that keeps customer-facing risk under control.', topic: 'monolith extraction', listType: 'number', listItems: ['Extract by business boundary, not technology layer.', 'Add anti-corruption boundary around shared contracts.', 'Shift traffic gradually with rollback checkpoints.'], quote: 'Migration speed is limited by observability quality.', quoteBy: 'Principal Engineer', status: 'in_review', type: 'article', featuredImageKey: 'remote-team', inlineImageKey: 'strategy', daysAgo: 84 },
  { title: 'Practical SLO Reviews for Product and Engineering', slug: 'practical-slo-reviews-for-product-and-engineering', description: 'Use shared SLO review rituals to align reliability tradeoffs with roadmap goals.', topic: 'slo governance', listType: 'bullet', listItems: ['Review burn events with feature launch timeline.', 'Set expiry dates for temporary reliability exceptions.', 'Link SLO debt directly to product milestones.'], quote: 'SLOs are negotiation tools, not punishment tools.', quoteBy: 'Product Reliability Group', status: 'published', type: 'article', featuredImageKey: 'strategy', inlineImageKey: 'dashboard', daysAgo: 90 },
  { title: 'Tenant-Aware Caching Patterns for Content APIs', slug: 'tenant-aware-caching-patterns-for-content-apis', description: 'Avoid cross-tenant bleed while keeping response latency predictable.', topic: 'tenant cache partitioning', listType: 'number', listItems: ['Scope cache keys with tenant identifiers.', 'Attach TTL policy by endpoint volatility.', 'Add cache poisoning checks in integration tests.'], quote: 'Shared infrastructure still needs isolated guarantees.', quoteBy: 'API Platform Team', status: 'published', type: 'article', featuredImageKey: 'deploy', inlineImageKey: 'pipeline', daysAgo: 96 },
  { title: 'Editorial Workflows That Reduce Publish-Day Surprises', slug: 'editorial-workflows-that-reduce-publish-day-surprises', description: 'Process checkpoints that improve content quality without slowing output.', topic: 'editorial quality workflow', listType: 'bullet', listItems: ['Run preflight checklist for links, metadata, and embeds.', 'Require explicit reviewer sign-off for high-traffic posts.', 'Track post-launch edits for recurring quality gaps.'], quote: 'Review quality is a release quality multiplier.', quoteBy: 'Content Operations Lead', status: 'published', type: 'article', featuredImageKey: 'docs', inlineImageKey: 'meeting', daysAgo: 101 },
  { title: 'Building a Rollback Culture for Safer Deployments', slug: 'building-a-rollback-culture-for-safer-deployments', description: 'Normalize rapid rollback as a quality control mechanism, not a failure.', topic: 'rollback operating model', listType: 'number', listItems: ['Define rollback criteria before deployment starts.', 'Practice rollback drills in staging every sprint.', 'Record rollback decision context in release notes.'], quote: 'Fast rollback is a sign of mature delivery.', quoteBy: 'Release Engineering', status: 'published', type: 'article', featuredImageKey: 'deploy', inlineImageKey: 'ops', daysAgo: 108 },
  { title: 'How Product Analytics and Support Data Should Meet', slug: 'how-product-analytics-and-support-data-should-meet', description: 'Create a shared evidence model between quantitative and qualitative feedback.', topic: 'joined product evidence', listType: 'bullet', listItems: ['Map ticket tags to analytics event dimensions.', 'Use weekly synthesis doc across product and support.', 'Prioritize fixes where both datasets align.'], quote: 'The strongest signal appears when data sources agree.', quoteBy: 'Growth Analyst', status: 'in_review', type: 'article', featuredImageKey: 'dashboard', inlineImageKey: 'war-room', daysAgo: 114 },
  { title: 'KPI Review Rituals for Engineering Managers', slug: 'kpi-review-rituals-for-engineering-managers', description: 'A practical cadence for reviewing delivery and reliability metrics with teams.', topic: 'engineering kpi cadence', listType: 'number', listItems: ['Review trend changes, not point-in-time spikes.', 'Pair each KPI with one proposed experiment.', 'Close the loop by checking outcomes next cycle.'], quote: 'Metrics are useful only when they change decisions.', quoteBy: 'VP Engineering', status: 'draft', type: 'article', featuredImageKey: 'cost', daysAgo: 120 },
  { title: 'Protecting Search Relevance During Rapid Catalog Growth', slug: 'protecting-search-relevance-during-rapid-catalog-growth', description: 'Index and ranking practices that keep search quality stable as content scales.', topic: 'search relevance governance', listType: 'bullet', listItems: ['Monitor zero-result and low-click query cohorts.', 'Schedule synonym and taxonomy updates monthly.', 'Audit ranking regressions before major launches.'], quote: 'Search quality degrades quietly without routine care.', quoteBy: 'Search Team', status: 'published', type: 'article', featuredImageKey: 'keyboard', inlineImageKey: 'dashboard', daysAgo: 126 },
  { title: 'Practical Release Notes Your Customers Will Read', slug: 'practical-release-notes-your-customers-will-read', description: 'Structure release notes for clarity, trust, and support deflection.', topic: 'customer-facing release notes', listType: 'number', listItems: ['Lead with customer outcome before implementation detail.', 'Group changes by workflow, not internal team.', 'Include known limitations and timeline for fixes.'], quote: 'Clarity in release notes lowers inbound support instantly.', quoteBy: 'Product Marketing', status: 'published', type: 'article', featuredImageKey: 'docs', inlineImageKey: 'docs', daysAgo: 132 },
  { title: 'Reducing Alert Fatigue Without Missing Real Incidents', slug: 'reducing-alert-fatigue-without-missing-real-incidents', description: 'Tune alerting around user impact to reduce noise and improve response quality.', topic: 'alert tuning', listType: 'bullet', listItems: ['Remove alerts with no concrete operator action.', 'Use composite signals for noisy systems.', 'Review false-positive ratio every sprint.'], quote: 'An ignored alert is already an outage in progress.', quoteBy: 'On-Call Lead', status: 'published', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'ops', daysAgo: 138 },
  { title: 'Dependency Upgrade Windows That Teams Can Sustain', slug: 'dependency-upgrade-windows-that-teams-can-sustain', description: 'Create predictable maintenance windows to avoid risky version jumps.', topic: 'dependency upgrade cadence', listType: 'number', listItems: ['Schedule monthly patch windows by service tier.', 'Automate compatibility checks for critical paths.', 'Publish exception policy for emergency upgrades.'], quote: 'Small upgrades often are safer than heroic upgrades rarely.', quoteBy: 'Security Engineering', status: 'in_review', type: 'article', featuredImageKey: 'pipeline', inlineImageKey: 'deploy', daysAgo: 145 },
  { title: 'Creating Better Technical RFCs in Distributed Teams', slug: 'creating-better-technical-rfcs-in-distributed-teams', description: 'Write RFCs that speed alignment and prevent asynchronous misunderstanding.', topic: 'distributed rfc quality', listType: 'bullet', listItems: ['Document constraints and rejected options explicitly.', 'Separate irreversible decisions from provisional ones.', 'Assign decision owner and follow-up date.'], quote: 'An RFC should reduce ambiguity, not just capture preferences.', quoteBy: 'Architecture Group', status: 'draft', type: 'article', featuredImageKey: 'remote-team', inlineImageKey: 'whiteboard', daysAgo: 151 },
  { title: 'Capacity Planning for APIs with Seasonal Traffic Peaks', slug: 'capacity-planning-for-apis-with-seasonal-traffic-peaks', description: 'Forecasting and guardrail techniques for predictable high-demand periods.', topic: 'seasonal capacity planning', listType: 'number', listItems: ['Model peak profile from prior seasonal campaigns.', 'Pre-scale critical dependencies with rollback checkpoints.', 'Run synthetic load tests against production-like limits.'], quote: 'Capacity planning is a business readiness activity.', quoteBy: 'Infrastructure Team', status: 'published', type: 'article', featuredImageKey: 'strategy', inlineImageKey: 'dashboard', daysAgo: 158 },
  { title: 'Cross-Functional Incident Communications That Build Trust', slug: 'cross-functional-incident-communications-that-build-trust', description: 'Operational communication patterns for high-stress reliability events.', topic: 'incident communication model', listType: 'bullet', listItems: ['Publish status updates on a fixed cadence.', 'Separate facts, hypotheses, and actions in updates.', 'Close incidents with customer-visible follow-up.'], quote: 'Trust grows when communication is specific and steady.', quoteBy: 'Customer Operations', status: 'published', type: 'article', featuredImageKey: 'meeting', inlineImageKey: 'war-room', daysAgo: 164 },
  { title: 'Meaningful A/B Test Readouts for Product Decisions', slug: 'meaningful-ab-test-readouts-for-product-decisions', description: 'Present experiment outcomes with confidence intervals and decision guidance.', topic: 'ab test decisioning', listType: 'number', listItems: ['Define stop criteria before running the test.', 'Report effect size and confidence, not only p-values.', 'Capture rollout recommendation with risk notes.'], quote: 'Experiments are useful when they end with a clear decision.', quoteBy: 'Product Analytics', status: 'published', type: 'article', featuredImageKey: 'dashboard', inlineImageKey: 'strategy', daysAgo: 171 },
  { title: 'Practical Data Contracts Between Application and BI Teams', slug: 'practical-data-contracts-between-application-and-bi-teams', description: 'Contract patterns that keep analytical reporting stable as product evolves.', topic: 'application to bi data contracts', listType: 'number', listItems: ['Version event schemas with compatibility policy.', 'Define ownership for every critical metric source.', 'Include BI validation checks in release pipeline.'], quote: 'Data contracts prevent silent metric drift.', quoteBy: 'Business Intelligence Lead', status: 'published', type: 'article', featuredImageKey: 'whiteboard', inlineImageKey: 'pipeline', daysAgo: 185 },
  { title: 'Security Patch Response Playbooks for Product Teams', slug: 'security-patch-response-playbooks-for-product-teams', description: 'Runbook structure for triage, remediation, and communication under vulnerability pressure.', topic: 'security patch operations', listType: 'bullet', listItems: ['Classify risk by exploitability and exposure.', 'Track mitigation and full remediation separately.', 'Communicate customer impact with plain language timelines.'], quote: 'Prepared playbooks buy time when vulnerabilities move fast.', quoteBy: 'Security Response Team', status: 'published', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'keyboard', daysAgo: 191 },
  { title: 'Improving Search and Recommendation Feedback Loops', slug: 'improving-search-and-recommendation-feedback-loops', description: 'Close the loop between user behavior signals and ranking model updates.', topic: 'search recommendation loop', listType: 'number', listItems: ['Capture explicit and implicit feedback events.', 'Define retraining cadence by catalog volatility.', 'Audit model drift with offline and online checks.'], quote: 'Ranking quality improves when feedback loops stay short.', quoteBy: 'ML Platform Team', status: 'in_review', type: 'article', featuredImageKey: 'dashboard', inlineImageKey: 'keyboard', daysAgo: 198 },
  { title: 'Designing Better Handoffs Between Product and Platform', slug: 'designing-better-handoffs-between-product-and-platform', description: 'Improve planning quality when product priorities depend on platform constraints.', topic: 'product platform handoff', listType: 'bullet', listItems: ['Start planning with explicit non-functional requirements.', 'Translate platform constraints into customer tradeoffs.', 'Review handoff quality in quarterly planning retro.'], quote: 'The handoff is where technical reality meets product ambition.', quoteBy: 'Program Management', status: 'published', type: 'article', featuredImageKey: 'meeting', inlineImageKey: 'whiteboard', daysAgo: 205 },
  { title: 'Editorial Calendar Planning with Operational Constraints', slug: 'editorial-calendar-planning-with-operational-constraints', description: 'Plan content output around staffing, review bandwidth, and launch dependencies.', topic: 'editorial operations planning', listType: 'number', listItems: ['Map calendar milestones to review capacity.', 'Reserve contingency slots for urgent communications.', 'Retrospect missed deadlines for systemic blockers.'], quote: 'Calendar realism protects quality under deadline pressure.', quoteBy: 'Head of Editorial', status: 'published', type: 'article', featuredImageKey: 'docs', inlineImageKey: 'meeting', daysAgo: 212 },
  { title: 'Sustainable Sprint Rituals for Hybrid Engineering Teams', slug: 'sustainable-sprint-rituals-for-hybrid-engineering-teams', description: 'Ritual adjustments that keep distributed teams aligned without meeting overload.', topic: 'hybrid sprint rituals', listType: 'bullet', listItems: ['Use async updates before synchronous standups.', 'Timebox planning around decision points, not ticket recitals.', 'Track meeting effectiveness with monthly team pulse.'], quote: 'Hybrid rhythm succeeds when async and live rituals complement each other.', quoteBy: 'People Operations Partner', status: 'published', type: 'article', featuredImageKey: 'remote-team', inlineImageKey: 'remote-team', daysAgo: 219 },
  { title: 'Post-Launch Monitoring Checklists That Catch Regressions Early', slug: 'post-launch-monitoring-checklists-that-catch-regressions-early', description: 'Short operational checklists to validate launches in the first 24 hours.', topic: 'post launch monitoring', listType: 'number', listItems: ['Watch core conversion and reliability signals hourly.', 'Compare new user paths against baseline cohorts.', 'Escalate anomalies with clear owner and expiry time.'], quote: 'The first day after launch decides recovery speed.', quoteBy: 'Release Manager', status: 'published', type: 'article', featuredImageKey: 'ops', inlineImageKey: 'dashboard', daysAgo: 226 },
]

const buildBodyParagraphs = (topic: string): string[] => [
  `Teams improve outcomes when ${topic} is treated as an ongoing operating practice rather than a one-time project.`,
  'The strongest implementations are explicit about ownership, measurable outcomes, and review cadence, which keeps improvements durable across staffing and roadmap changes.',
]

const buildCodeSnippet = (slug: string) => `seed.post({\n  slug: '${slug}',\n  mode: 'create-missing',\n  track: ['created', 'skipped', 'failed']\n})`

export const seededPosts: SeedPost[] = blueprints.map((entry, index) => ({
  title: entry.title,
  slug: entry.slug,
  description: entry.description,
  content: {
    intro: `This guide focuses on ${entry.topic} with practical implementation details that product, engineering, and operations can apply immediately.`,
    body: buildBodyParagraphs(entry.topic),
    listType: entry.listType,
    listItems: entry.listItems,
    quote: {
      text: entry.quote,
      by: entry.quoteBy,
    },
    code: index % 3 === 0 ? { language: 'typescript', snippet: buildCodeSnippet(entry.slug) } : undefined,
    inlineImageKey: entry.inlineImageKey,
  },
  status: entry.status,
  type: entry.type,
  featuredImageKey: entry.featuredImageKey,
  publishedAt: isoDaysAgo(entry.daysAgo),
}))

export const seededPostSlugs = seededPosts.map((post) => post.slug)
