/**
 * Script to assign default tenant to all users and documents
 * Works with junction table structure (users_tenants)
 *
 * Run: pnpm exec tsx src/scripts/assign-default-tenant-v2.ts
 */

import pg from 'pg';
import dotenv from 'dotenv';
import { resolve } from 'path';
import { randomUUID } from 'crypto';

// Load environment variables
dotenv.config({ path: resolve(process.cwd(), '.env') });

async function assignDefaultTenant() {
  const connectionString = process.env.PAYLOAD_DATABASE_URI || process.env.DATABASE_URI;

  if (!connectionString) {
    console.error('Error: PAYLOAD_DATABASE_URI or DATABASE_URI environment variable is required');
    process.exit(1);
  }

  const client = new pg.Client({ connectionString });

  try {
    await client.connect();
    console.log('Assigning default tenant to users and documents...\n');

    // Get default tenant
    const tenantResult = await client.query(`
      SELECT id FROM tenants WHERE slug = 'default' LIMIT 1;
    `);

    if (!tenantResult.rows || tenantResult.rows.length === 0) {
      console.error('Error: Default tenant not found. Please create a tenant first.');
      process.exit(1);
    }

    const tenantId = tenantResult.rows[0].id;
    console.log(`✓ Found default tenant (ID: ${tenantId})\n`);

    // Check users_tenants table structure
    const tableCheck = await client.query(`
      SELECT column_name
      FROM information_schema.columns
      WHERE table_name = 'users_tenants';
    `);

    if (tableCheck.rows.length === 0) {
      console.error('Error: users_tenants table does not exist. Schema may not be fully created.');
      process.exit(1);
    }

    console.log('users_tenants table structure:');
    tableCheck.rows.forEach((row: any) => {
      console.log(`  - ${row.column_name}`);
    });
    console.log('');

    // Assign tenant to all users via junction table
    console.log('Step 1: Assigning tenant to users...');
    const usersResult = await client.query(`
      SELECT id, email FROM users;
    `);

    let usersUpdated = 0;
    for (const user of usersResult.rows) {
      // Check if relationship already exists
      // _parent_id is the user ID, tenant_id is the tenant ID
      const existing = await client.query(`
        SELECT id FROM users_tenants
        WHERE _parent_id = $1 AND tenant_id = $2;
      `, [user.id, tenantId]);

      if (existing.rows.length === 0) {
        // Insert relationship
        // _parent_id = user ID, tenant_id = tenant ID, _order = sort order
        // id will be auto-generated by the database
        try {
          await client.query(`
            INSERT INTO users_tenants (_parent_id, tenant_id, _order)
            VALUES ($1, $2, 0);
          `, [user.id, tenantId]);
        } catch (error: any) {
          // Ignore duplicate key errors (relationship might have been created between check and insert)
          if (error.code !== '23505') {
            throw error;
          }
        }

        usersUpdated++;
        console.log(`  ✓ Assigned tenant to user: ${user.email}`);
      }
    }

    if (usersUpdated === 0) {
      console.log('  ✓ All users already have tenant assigned');
    } else {
      console.log(`  ✓ Updated ${usersUpdated} users`);
    }

    // Assign tenant to all tenant-scoped documents
    console.log('\nStep 2: Assigning tenant to documents...');

    const tenantScopedCollections = [
      'spaces',
      'posts',
      'pages',
      'categories',
      'tags',
      'forms',
      'form_fields',
      'form_submissions',
      'form_submission_values'
    ];

    let totalDocsUpdated = 0;
    for (const collection of tenantScopedCollections) {
      try {
        // Check if table exists and has tenant column
        const tableCheck = await client.query(`
          SELECT column_name
          FROM information_schema.columns
          WHERE table_name = $1 AND column_name = 'tenant';
        `, [collection]);

        if (tableCheck.rows.length === 0) {
          continue; // Table or column doesn't exist yet
        }

        // Update documents without tenant
        const updateResult = await client.query(`
          UPDATE ${collection}
          SET tenant = $1
          WHERE tenant IS NULL;
        `, [tenantId]);

        if (updateResult.rowCount && updateResult.rowCount > 0) {
          console.log(`  ✓ Updated ${updateResult.rowCount} documents in ${collection}`);
          totalDocsUpdated += updateResult.rowCount;
        }
      } catch (error: any) {
        // Table might not exist yet - that's okay
        if (error.code !== '42P01') {
          console.warn(`  ⚠ Error updating ${collection}:`, error.message);
        }
      }
    }

    if (totalDocsUpdated > 0) {
      console.log(`\n  ✓ Updated ${totalDocsUpdated} total documents`);
    } else {
      console.log('\n  ✓ All documents already have tenant assigned (or no documents exist yet)');
    }

    console.log('\n✅ Default tenant assignment complete!');
    console.log('\nNext steps:');
    console.log('1. Restart your Payload dev server');
    console.log('2. You should now be able to see documents');
    console.log('3. The tenants dropdown in registration should work');
  } catch (error) {
    console.error('Error assigning tenant:', error);
    throw error;
  } finally {
    await client.end();
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  assignDefaultTenant()
    .then(() => {
      console.log('\nScript completed');
      process.exit(0);
    })
    .catch((error) => {
      console.error('\nScript failed:', error);
      process.exit(1);
    });
}

export default assignDefaultTenant;

